services:
  service:
    build: .
    tty: true
    ports:
      - '8096:${APP_PORT}'
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/src/node_modules
      - ./files:/app/files
    env_file:
      - .env
    depends_on:
      - app-database
  app-database:
    image: postgres:14.2
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'root', '-W']
      timeout: 45s
      interval: 5s
      retries: 10
    ports:
      - ${EXPOSED_DB_PORT:-5446}:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      event-streaming-bridge:
      default:
        aliases:
          - ${HOST_PUBLIC}
volumes:
  database-data:
networks:
  event-streaming-bridge:
    name: event_streaming_bridge
    driver: bridge
